### ISSUE TITLE
Entregable Product Backlog 1

### ISSUE THREAD

**Issue by RositaTorres** [RositaTorres/Proyecto-Empresa-Servicios-Exequiales#20]

**Comment by Carolinrg** [comment]
- [x]  Entregable definitivo


[Sprint1_Teamdevelopersoft.docx](https://github.com/RositaTorres/Proyecto-Empresa-Servicios-Exequiales/files/9430083/Sprint1_Teamdevelopersoft.docx)


- [x] Subir el video al drive
