### ISSUE TITLE
Sprint 2 Semana 3 - 2 Modelar un  empleado como  una clase de Java

### ISSUE THREAD

**Issue by Carolinrg** [RositaTorres/Proyecto-Empresa-Servicios-Exequiales#8]

**Comment by SADIDROMERO** [comment]
- [x] Es posible crear una nueva instancia de la clase "Empleado" 
- [x] Es posible leer y modificar el nombre de un empleado 
- [x] Es posible leer y modificar el correo de un empleado 
- [x] Es posible leer y modificar la empresa a la que el empleado pertenece 
- [x] Es posible leer y modificar el rol del empleado (administrador, operativo)
