### ISSUE TITLE
Sprint 2 Semana 3 -  3 Modelar el  movimiento de  dinero como una  clase de Java

### ISSUE THREAD

**Issue by Carolinrg** [RositaTorres/Proyecto-Empresa-Servicios-Exequiales#9]

**Comment by SADIDROMERO** [comment]
- [x] Es posible crear una nueva instancia de la clase "MovimientoDinero" 
- [x] Es posible leer y modificar el monto del movimiento 
- [x] Es posible crear montos positivos y negativos 
- [x] Es posible leer y modificar el concepto del movimiento 
- [x] Es posible definir qué usuario fue encargado de registrar el movimiento

**Comment by Carolinrg** [comment]
Solicitar una tutoria para aclaracion el dia miercoles 31

**Comment by Carolinrg** [comment]
Se realiza tutoría y con ella evidenciamos que cumplimos con el requerimiento del Sprint
